version: "3.9"  # optional since v1.27.0
services:
  database:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  lleidahack:
    build: .
    volumes:
      - ./static:/app/static
      - ./config.ini:/config.ini
