"""empty message

Revision ID: 19a69372d0ba
Revises: a8455b9b130e
Create Date: 2024-03-01 17:32:18.302051

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '19a69372d0ba'
down_revision = 'a8455b9b130e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
