"""empty message

Revision ID: 1a51cf92d21c
Revises: 6a212e0e0b92
Create Date: 2024-02-15 22:35:32.997692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a51cf92d21c'
down_revision = '6a212e0e0b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reciveNotifications', sa.Boolean(), nullable=True),
    sa.Column('defaultLang', sa.String(), nullable=True),
    sa.Column('comercialNotifications', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_index(op.f('ix_user-config_id'), 'user-config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user-config_id'), table_name='user-config')
    op.drop_table('user-config')
    # ### end Alembic commands ###
