"""empty message

Revision ID: eb5796b93841
Revises: 83b72cd40dab
Create Date: 2024-09-23 23:42:10.913359

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'eb5796b93841'
down_revision = '83b72cd40dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('tier', sa.Integer(), nullable=True))
    op.execute("UPDATE company SET tier=0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'tier')
    # ### end Alembic commands ###
