"""empty message

Revision ID: 20bff18796a3
Revises: 83b72cd40dab
Create Date: 2024-09-23 22:37:39.866908

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20bff18796a3'
down_revision = '83b72cd40dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('tier', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'tier')
    # ### end Alembic commands ###
