"""empty message

Revision ID: ff2260a2296f
Revises: beb25bc83663
Create Date: 2024-03-20 18:40:34.713284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2260a2296f'
down_revision = 'beb25bc83663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reciveNotifications', sa.Boolean(), nullable=True),
    sa.Column('defaultLang', sa.String(), nullable=True),
    sa.Column('comercialNotifications', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['my_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_config_id'), 'user_config', ['id'], unique=True)
    #op.alter_column('company_user', 'active',
    #           existing_type=sa.INTEGER(),
    #           type_=sa.Boolean(),
    #           existing_nullable=True)
    op.add_column('my_user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('my_user', sa.Column('config_id', sa.Integer(), nullable=True))
    # op.drop_index('ix_user_code', table_name='my_user')
    # op.drop_index('ix_user_email', table_name='my_user')
    # op.drop_index('ix_user_id', table_name='my_user')
    # op.drop_index('ix_user_nickname', table_name='my_user')
    # op.drop_index('ix_user_telephone', table_name='my_user')
    # op.create_index(op.f('ix_my_user_code'), 'my_user', ['code'], unique=True)
    # op.create_index(op.f('ix_my_user_email'), 'my_user', ['email'], unique=True)
    # op.create_index(op.f('ix_my_user_id'), 'my_user', ['id'], unique=False)
    # op.create_index(op.f('ix_my_user_nickname'), 'my_user', ['nickname'], unique=True)
    # op.create_index(op.f('ix_my_user_telephone'), 'my_user', ['telephone'], unique=True)
    op.create_foreign_key(None, 'my_user', 'user_config', ['config_id'], ['id'])
    op.drop_column('my_user', 'is_image_url')
    op.drop_column('my_user', 'recive_mails')
    op.drop_column('my_user', 'lleidacoins_claimed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_user', sa.Column('lleidacoins_claimed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('my_user', sa.Column('recive_mails', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('my_user', sa.Column('is_image_url', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'my_user', type_='foreignkey')
    op.drop_index(op.f('ix_my_user_telephone'), table_name='my_user')
    op.drop_index(op.f('ix_my_user_nickname'), table_name='my_user')
    op.drop_index(op.f('ix_my_user_id'), table_name='my_user')
    op.drop_index(op.f('ix_my_user_email'), table_name='my_user')
    op.drop_index(op.f('ix_my_user_code'), table_name='my_user')
    op.create_index('ix_user_telephone', 'my_user', ['telephone'], unique=True)
    op.create_index('ix_user_nickname', 'my_user', ['nickname'], unique=True)
    op.create_index('ix_user_id', 'my_user', ['id'], unique=False)
    op.create_index('ix_user_email', 'my_user', ['email'], unique=True)
    op.create_index('ix_user_code', 'my_user', ['code'], unique=True)
    op.drop_column('my_user', 'config_id')
    op.drop_column('my_user', 'is_deleted')
    op.alter_column('company_user', 'active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_config_id'), table_name='user_config')
    op.drop_table('user_config')
    # ### end Alembic commands ###
