"""empty message

Revision ID: 8a4d98b6c642
Revises: 847a5f6da4fb
Create Date: 2024-04-25 16:14:30.007769

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8a4d98b6c642"
down_revision = "847a5f6da4fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("reciveNotifications", sa.Boolean(), nullable=True),
        sa.Column("defaultLang", sa.String(), nullable=True),
        sa.Column("comercialNotifications", sa.Boolean(), nullable=True),
        sa.Column("terms_and_conditions", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_config_id"),
                    "user_config", ["id"],
                    unique=True)
    op.drop_column("company", "is_image_url")
    op.drop_column("event", "is_image_url")
    op.add_column("my_user",
                  sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("my_user", sa.Column("config_id",
                                       sa.Integer(),
                                       nullable=True))
    op.drop_constraint("uq_my_user_code", "my_user", type_="unique")
    op.create_foreign_key("fk_my_user_user_config", "my_user", "user_config",
                          ["config_id"], ["id"])
    op.drop_column("my_user", "terms_accepted")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "my_user",
        sa.Column("terms_accepted",
                  sa.BOOLEAN(),
                  autoincrement=False,
                  nullable=True),
    )
    op.drop_constraint("fk_my_user_user_config", "my_user", type_="foreignkey")
    op.create_unique_constraint("uq_my_user_code", "my_user", ["code"])
    op.drop_column("my_user", "config_id")
    op.drop_column("my_user", "is_deleted")
    op.add_column(
        "event",
        sa.Column("is_image_url",
                  sa.BOOLEAN(),
                  autoincrement=False,
                  nullable=True),
    )
    op.add_column(
        "company",
        sa.Column("is_image_url",
                  sa.BOOLEAN(),
                  autoincrement=False,
                  nullable=True),
    )
    op.drop_index(op.f("ix_user_config_id"), table_name="user_config")
    op.drop_table("user_config")
    # ### end Alembic commands ###
