"""empty message

Revision ID: fe3ee996c4ab
Revises: 20e9f9db44d3
Create Date: 2024-03-05 11:30:04.544319

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fe3ee996c4ab'
down_revision = '20e9f9db44d3'
branch_labels = None
depends_on = None

##TODO: Fer primer lo del cascade i despres borrar aixo i fer un altre Autogenerate ficant els noms que s'han ficat aqui. el 'fkey_user_id_user_config' i el 'fkey_user_config_user_id'.


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_config',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reciveNotifications', sa.Boolean(), nullable=True),
        sa.Column('defaultLang', sa.String(), nullable=True),
        sa.Column('comercialNotifications', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='fkey_user_config_user_id'),
        sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_user_config_id'),
                    'user_config', ['id'],
                    unique=True)
    op.add_column('user', sa.Column('config_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fkey_user_id_user_config', 'user', 'user_config',
                          ['config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fkey_user_id_user_config', 'user', type_='foreignkey')
    op.drop_column('user', 'config_id')
    op.drop_index(op.f('ix_user_config_id'), table_name='user_config')
    op.drop_table('user_config')
    # ### end Alembic commands ###
