"""empty message

Revision ID: 4fc9fa836842
Revises: ff2260a2296f
Create Date: 2024-03-21 16:09:07.827396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc9fa836842'
down_revision = 'ff2260a2296f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('company_user', 'active',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    # op.drop_index('ix_user_code', table_name='my_user')
    # op.drop_index('ix_user_email', table_name='my_user')
    # op.drop_index('ix_user_id', table_name='my_user')
    # op.drop_index('ix_user_nickname', table_name='my_user')
    # op.drop_index('ix_user_telephone', table_name='my_user')
    # op.create_index(op.f('ix_my_user_code'), 'my_user', ['code'], unique=True)
    # op.create_index(op.f('ix_my_user_email'), 'my_user', ['email'], unique=True)
    # op.create_index(op.f('ix_my_user_id'), 'my_user', ['id'], unique=False)
    # op.create_index(op.f('ix_my_user_nickname'), 'my_user', ['nickname'], unique=True)
    # op.create_index(op.f('ix_my_user_telephone'), 'my_user', ['telephone'], unique=True)
    op.drop_column('my_user', 'terms_accepted')
    op.drop_constraint('user_config_user_id_fkey', 'user_config', type_='foreignkey')
    op.drop_column('user_config', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_config', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_config_user_id_fkey', 'user_config', 'my_user', ['user_id'], ['id'])
    op.add_column('my_user', sa.Column('terms_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # op.drop_index(op.f('ix_my_user_telephone'), table_name='my_user')
    # op.drop_index(op.f('ix_my_user_nickname'), table_name='my_user')
    # op.drop_index(op.f('ix_my_user_id'), table_name='my_user')
    # op.drop_index(op.f('ix_my_user_email'), table_name='my_user')
    # op.drop_index(op.f('ix_my_user_code'), table_name='my_user')
    # op.create_index('ix_user_telephone', 'my_user', ['telephone'], unique=True)
    # op.create_index('ix_user_nickname', 'my_user', ['nickname'], unique=True)
    # op.create_index('ix_user_id', 'my_user', ['id'], unique=False)
    # op.create_index('ix_user_email', 'my_user', ['email'], unique=True)
    # op.create_index('ix_user_code', 'my_user', ['code'], unique=True)
    # op.alter_column('company_user', 'active',
    #            existing_type=sa.Boolean(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # ### end Alembic commands ###
