"""empty message

Revision ID: 83b72cd40dab
Revises: 082e0feb242a
Create Date: 2024-09-23 13:42:04.201286

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "83b72cd40dab"
down_revision = "082e0feb242a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hacker_event_registration",
        sa.Column("wants_credit", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hacker_event_registration", "wants_credit")
    # ### end Alembic commands ###
