"""empty message

Revision ID: f8b5edebc3b2
Revises: 17ef489bd284
Create Date: 2024-03-28 02:13:27.613203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b5edebc3b2'
down_revision = '17ef489bd284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'is_image_url')
    op.drop_column('event', 'is_image_url')
    ##TODO: Repasar amb el ton a ver si aixo es necesari. Només cambia el nom i el problema es que son keys depenents a altres taules i salta error.
    # op.drop_index('ix_user_code', table_name='my_user')
    # op.drop_index('ix_user_email', table_name='my_user')
    # op.drop_index('ix_user_id', table_name='my_user')
    # op.drop_index('ix_user_nickname', table_name='my_user')
    # op.drop_index('ix_user_telephone', table_name='my_user')
    # op.create_index(op.f('ix_my_user_code'), 'my_user', ['code'], unique=True)
    # op.create_index(op.f('ix_my_user_email'), 'my_user', ['email'], unique=True)
    # op.create_index(op.f('ix_my_user_id'), 'my_user', ['id'], unique=False)
    # op.create_index(op.f('ix_my_user_nickname'), 'my_user', ['nickname'], unique=True)
    # op.create_index(op.f('ix_my_user_telephone'), 'my_user', ['telephone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_my_user_telephone'), table_name='my_user')
    # op.drop_index(op.f('ix_my_user_nickname'), table_name='my_user')
    # op.drop_index(op.f('ix_my_user_id'), table_name='my_user')
    # op.drop_index(op.f('ix_my_user_email'), table_name='my_user')
    # op.drop_index(op.f('ix_my_user_code'), table_name='my_user')
    # op.create_index('ix_user_telephone', 'my_user', ['telephone'], unique=True)
    # op.create_index('ix_user_nickname', 'my_user', ['nickname'], unique=True)
    # op.create_index('ix_user_id', 'my_user', ['id'], unique=False)
    # op.create_index('ix_user_email', 'my_user', ['email'], unique=True)
    # op.create_index('ix_user_code', 'my_user', ['code'], unique=True)
    op.add_column('event', sa.Column('is_image_url', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('is_image_url', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
