"""empty message

Revision ID: 3a33221075f6
Revises: 7db37f8120cc
Create Date: 2023-08-16 00:22:00.945564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a33221075f6'
down_revision = '7db37f8120cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_user', sa.Column('active', sa.Integer(), nullable=True))
    op.add_column('hacker_group', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_hacker_group_code'), 'hacker_group', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hacker_group_code'), table_name='hacker_group')
    op.drop_column('hacker_group', 'code')
    op.drop_column('company_user', 'active')
    # ### end Alembic commands ###
