"""empty message

Revision ID: 6432c69a86c9
Revises: 5e5b3cecd565
Create Date: 2024-03-01 18:24:16.411131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6432c69a86c9'
down_revision = '5e5b3cecd565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
