"""empty message

Revision ID: 91492fa927a3
Revises: dfd2ca4ab802
Create Date: 2024-03-01 18:15:26.613716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91492fa927a3'
down_revision = 'dfd2ca4ab802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
