"""empty message

Revision ID: 9f8fb6880207
Revises: 3a33221075f6
Create Date: 2023-08-18 12:15:42.350045

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9f8fb6880207'
down_revision = '3a33221075f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('leader_id',
                                       sa.Integer(),
                                       nullable=True))
    op.create_foreign_key(None, 'company', 'user', ['leader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'leader_id')
    # ### end Alembic commands ###
