"""empty message

Revision ID: a2ac322dab0a
Revises: 91492fa927a3
Create Date: 2024-03-01 18:20:27.690046

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a2ac322dab0a'
down_revision = '91492fa927a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_config_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'config_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('config_id',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True))
    op.create_foreign_key('user_config_id_fkey', 'user', 'user-config',
                          ['config_id'], ['id'])
    # ### end Alembic commands ###
