"""empty message

Revision ID: a8455b9b130e
Revises: 8c7539990328
Create Date: 2024-03-01 12:59:25.996121

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a8455b9b130e'
down_revision = '8c7539990328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('config_id', sa.Integer(), nullable=True))
    op.drop_index('ix_user-config_id', table_name='user-config')
    op.create_index(op.f('ix_user-config_id'),
                    'user-config', ['id'],
                    unique=True)
    op.create_foreign_key(None, 'user', 'user-config', ['config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user-config_id'), table_name='user-config')
    op.create_index('ix_user-config_id', 'user-config', ['id'], unique=False)
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'config_id')
    # ### end Alembic commands ###
