"""empty message

Revision ID: b283ec33eb72
Revises: 6432c69a86c9
Create Date: 2024-03-01 18:24:51.669917

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b283ec33eb72'
down_revision = '6432c69a86c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
