"""empty message

Revision ID: bdfffa261604
Revises: e34ea7ccc7a5
Create Date: 2024-03-01 17:59:48.746047

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bdfffa261604'
down_revision = 'e34ea7ccc7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user-config',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reciveNotifications', sa.Boolean(), nullable=True),
        sa.Column('defaultLang', sa.String(), nullable=True),
        sa.Column('comercialNotifications', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_user-config_id'),
                    'user-config', ['id'],
                    unique=True)
    op.add_column('user', sa.Column('config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user-config', ['config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'config_id')
    op.drop_index(op.f('ix_user-config_id'), table_name='user-config')
    op.drop_table('user-config')
    # ### end Alembic commands ###
