"""empty message

Revision ID: dfd2ca4ab802
Revises: bdfffa261604
Create Date: 2024-03-01 18:14:56.963103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd2ca4ab802'
down_revision = 'bdfffa261604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
