"""empty message

Revision ID: e34ea7ccc7a5
Revises: 758241c4720f
Create Date: 2024-03-01 17:56:00.498852

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e34ea7ccc7a5'
down_revision = '758241c4720f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_config_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'config_id')
    op.drop_index('ix_user-config_id', table_name='user-config')
    op.drop_table('user-config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('config_id',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True))
    op.create_foreign_key('user_config_id_fkey', 'user', 'user-config',
                          ['config_id'], ['id'])
    op.create_table(
        'user-config',
        sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('reciveNotifications',
                  sa.BOOLEAN(),
                  autoincrement=False,
                  nullable=True),
        sa.Column('defaultLang',
                  sa.VARCHAR(),
                  autoincrement=False,
                  nullable=True),
        sa.Column('comercialNotifications',
                  sa.BOOLEAN(),
                  autoincrement=False,
                  nullable=True),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False,
                  nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='user-config_user_id_fkey'))
    op.create_index('ix_user-config_id', 'user-config', ['id'], unique=True)
    # ### end Alembic commands ###
