from src.impl.Article import model  # noqa: F401
from src.impl.ArticleType import model  # noqa: F401
from src.impl.Company import model  # noqa: F401
from src.impl.CompanyUser import model  # noqa: F401
from src.impl.Event import model  # noqa: F401
from src.impl.Hacker import model  # noqa: F401
from src.impl.HackerGroup import model  # noqa: F401
from src.impl.LleidaHacker import model  # noqa: F401
from src.impl.LleidaHackerGroup import model  # noqa: F401
from src.impl.Meal import model  # noqa: F401
from src.impl.Notification import model  # noqa: F401
from src.impl.User import model  # noqa: F401
from src.impl.UserConfig import model  # noqa: F401
