name: resetDatabse
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%H:%M_%d-%m-%Y')"
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}/${{ steps.extract_branch.outputs.branch }}
            psql -d test -c "DROP DATABASE backend_${{ steps.extract_branch.outputs.branch }};"
            psql -d test -c "CREATE DATABASE backend_${{ steps.extract_branch.outputs.branch }};"
            psql -d echo backend_${{ steps.extract_branch.outputs.branch }} -c "GRANT ALL PRIVILEGES ON DATABASE backend_${{ steps.extract_branch.outputs.branch }} TO backend;"
            alembic upgrade head